# Generated by Django 2.1 on 2018-08-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fort', '0003_auto_20180813_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=128, unique=True, verbose_name='堡垒机用户组名'),
        ),
        migrations.AlterField(
            model_name='host',
            name='port',
            field=models.IntegerField(default=22, verbose_name='端口'),
        ),
    ]
