# Generated by Django 2.1 on 2018-08-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fort', '0004_auto_20180813_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='release',
            field=models.CharField(default='CentOS', max_length=191, verbose_name='发行版本'),
        ),
        migrations.AlterField(
            model_name='jenkinslist',
            name='build_url',
            field=models.CharField(max_length=191, verbose_name='项目url'),
        ),
        migrations.AlterField(
            model_name='remoteuser',
            name='password',
            field=models.CharField(max_length=191),
        ),
    ]
