# Generated by Django 2.1 on 2018-08-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fort', '0005_auto_20180813_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='log_type',
            field=models.CharField(choices=[('0', 'DEBUG'), ('1', 'INFO'), ('2', 'WARNING'), ('3', 'ERROR'), ('4', 'CRITICAL')], default='1', max_length=50, verbose_name='日志类型'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='堡垒机用户组名'),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='远程主机名'),
        ),
        migrations.AlterField(
            model_name='host',
            name='release',
            field=models.CharField(default='CentOS', max_length=150, verbose_name='发行版本'),
        ),
        migrations.AlterField(
            model_name='jenkinslist',
            name='build_url',
            field=models.CharField(max_length=150, verbose_name='项目url'),
        ),
        migrations.AlterField(
            model_name='jenkinslist',
            name='job_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Jenkins项目名'),
        ),
        migrations.AlterField(
            model_name='remoteuser',
            name='password',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='remoteuser',
            name='remote_user_name',
            field=models.CharField(max_length=100, verbose_name='远程主机用户名'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('0', '普通用户'), ('1', '超级用户')], default='0', max_length=100, verbose_name='用户类型'),
        ),
    ]
