# Generated by Django 2.1 on 2018-08-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fort', '0007_hostgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostgroup',
            name='remote_host_bind_hosts',
        ),
        migrations.RemoveField(
            model_name='group',
            name='memo',
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='堡垒机用户组名'),
        ),
        migrations.DeleteModel(
            name='HostGroup',
        ),
    ]
