# Generated by Django 2.1.1 on 2018-09-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lianjia3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lianjia3',
            name='attention',
            field=models.CharField(max_length=255, verbose_name='关注人数'),
        ),
        migrations.AlterField(
            model_name='lianjia3',
            name='buildingtype',
            field=models.CharField(max_length=255, verbose_name='建筑类型'),
        ),
        migrations.AlterField(
            model_name='lianjia3',
            name='buildyear',
            field=models.CharField(max_length=255, verbose_name='建设年代'),
        ),
        migrations.AlterField(
            model_name='lianjia3',
            name='constructionArea',
            field=models.CharField(max_length=255, verbose_name='建筑面积'),
        ),
        migrations.AlterField(
            model_name='lianjia3',
            name='decorationType',
            field=models.CharField(max_length=255, verbose_name='装修类型'),
        ),
        migrations.AlterField(
            model_name='lianjia3',
            name='floor',
            field=models.CharField(max_length=255, verbose_name='所在楼层'),
        ),
        migrations.AlterField(
            model_name='lianjia3',
            name='hasElevator',
            field=models.CharField(max_length=255, verbose_name='是否电梯'),
        ),
        migrations.AlterField(
            model_name='lianjia3',
            name='houseType',
            field=models.CharField(max_length=255, verbose_name='房屋户型'),
        ),
        migrations.AlterField(
            model_name='lianjia3',
            name='last30DayLead',
            field=models.CharField(max_length=255, verbose_name='30天带看'),
        ),
        migrations.AlterField(
            model_name='lianjia3',
            name='lastSell',
            field=models.CharField(max_length=255, verbose_name='上次交易'),
        ),
        migrations.AlterField(
            model_name='lianjia3',
            name='title',
            field=models.CharField(max_length=255, verbose_name='房屋标题'),
        ),
        migrations.AlterField(
            model_name='lianjia3',
            name='totalPrice',
            field=models.CharField(max_length=255, verbose_name='房屋总价'),
        ),
        migrations.AlterField(
            model_name='lianjia3',
            name='toward',
            field=models.CharField(max_length=255, verbose_name='房屋朝向'),
        ),
        migrations.AlterField(
            model_name='lianjia3',
            name='useful',
            field=models.CharField(max_length=255, verbose_name='房屋用途'),
        ),
        migrations.AlterField(
            model_name='lianjia3',
            name='yearOfRight',
            field=models.CharField(max_length=255, verbose_name='产权年限'),
        ),
    ]
