- name: ensure redis is at the latest version
  yum: pkg=redis state=latest
- name: create the redis config file
  template: src=redis.conf.j2 dest=/etc/redis.conf owner=root group=root mode=0644 
- name: start redis 
  service: name=redis state=started enabled=yes 
#  handlers: 
#    - name: restart redis 
#      service: name=redis state=restarted
